# app/config/security.yml
security:
    firewalls:
        frontend:
            pattern:     ^/*
            anonymous:   ~
            form_login:
                login_path:          usuario_login          # /usuario/login
                check_path:          usuario_login_check    # /usuario/login_check
                use_referer:         true                   # redirige a la página que quería ir el usuario antes del login (opción por defecto)
                default_target_path: /usuario/compras       # cuando no se puede obtener la página anterior o el usuario accede al login directamente
                always_use_default_target_path: true        # para redirigir a todos los usuarios a la misma página
            remember_me:
                key:                 cupon1234
                lifetime:            3600

    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }

    providers:
        usuarios:
            entity: { class: Cupon\UsuarioBundle\Entity\Usuario, property: email }

    encoders:
        Cupon\UsuarioBundle\Entity\Usuario: plaintext

